name: Build

on:
  push:
    tags:
    - 'latest'
    - 'v*'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-generator:
    name: 'Build Generator'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: recursive

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      
      - name: Install
        run: npm ci
        working-directory: ./src/generator
      
      - name: Lint
        run: npm run lint
        working-directory: ./src/generator

      - name: Check Types
        run: npm run check-types
        working-directory: ./src/generator

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

  build-autorest:
    name: 'Build Autorest.Bicep'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: recursive

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      
      - name: Build bicep-types dependency
        run: |
          npm ci
          npm run build
        working-directory: bicep-types/src/bicep-types
      
      - name: Install
        run: npm ci
        working-directory: ./src/autorest.bicep
      
      - name: Lint
        run: npm run lint
        working-directory: ./src/autorest.bicep

      - name: Build
        run: npm run build
        working-directory: ./src/autorest.bicep
      
      - name: Test
        run: npm test
        working-directory: ./src/autorest.bicep

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4